package alexgit95.batch.googleLocationsExtractor.dao.entities;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.persistence.*;


@DynamoDBTable(tableName="Positions")
@Entity
public class LocationsOutput {
	@Id
	private String id;
	@Column
	private String name;
	@Column
	private String address;
	@Column
	private double lattitude;
	@Column
	private double longitude;
	@Column
	private Date begin;
	@Column(name="endtime")
	private Date end;
	
	
	
	
	public LocationsOutput() {
		super();
	}
	
	
	public LocationsOutput(String id, String name, String address, double lattitude, double longitude, Date begin,
			Date end) {
		super();
		this.id = id;
		this.name = name;
		this.address = address;
		this.lattitude = lattitude;
		this.longitude = longitude;
		this.begin = begin;
		this.end = end;
	}


	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName="name")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute(attributeName="address")
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	
	
	@DynamoDBAttribute(attributeName="lattitude")
	public double getLattitude() {
		return lattitude;
	}
	public void setLattitude(double lattitude) {
		this.lattitude = lattitude;
	}
	@DynamoDBAttribute(attributeName="longitude")
	public double getLongitude() {
		return longitude;
	}
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	@DynamoDBAttribute(attributeName="date")
	public Date getBegin() {
		return begin;
	}
	public void setBegin(Date begin) {
		this.begin = begin;
	}
	@DynamoDBAttribute(attributeName="enddate")
	public Date getEnd() {
		return end;
	}
	public void setEnd(Date end) {
		this.end = end;
	}





	@Override
	public String toString() {
		return "LocationsOutput [id=" + id + ", name=" + name + ", address=" + address + ", lattitude=" + lattitude
				+ ", longitude=" + longitude + ", begin=" + begin + ", end=" + end + "]";
	}
	
	
}
