package alexgit95.batch.googleLocationsExtractor.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="IgnorePlaces")
public class IgnorePlace {
	
	private String id;
	private double lattitude;
	private double longitude;
	private String libelle;
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName="lattitude")
	public double getLattitude() {
		return lattitude;
	}
	public void setLattitude(double lattitude) {
		this.lattitude = lattitude;
	}
	@DynamoDBAttribute(attributeName="longitude")
	public double getLongitude() {
		return longitude;
	}
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	public String getLibelle() {
		return libelle;
	}
	
	@DynamoDBAttribute(attributeName="libelle")
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}
	public IgnorePlace(String id, double lattitude, double longitude, String libelle) {
		super();
		this.id = id;
		this.lattitude = lattitude;
		this.longitude = longitude;
		this.libelle = libelle;
	}
	public IgnorePlace() {
		super();
	}
	@Override
	public String toString() {
		return "IgnorePlace [id=" + id + ", lattitude=" + lattitude + ", longitude=" + longitude + ", libelle="
				+ libelle + "]";
	}
	
	

}
